/**
 * ChronicleIdle asset pipeline. Reads the owner's sources in /game/assets and writes optimised,
 * content-hashed files to public/assets/generated plus a typed manifest (docs/tech/ARCHITECTURE.md §8).
 *
 *   tsx tools/assets/build.ts [--quiet] [--force] [--check]
 */
import { existsSync, readFileSync } from 'node:fs';
import { readFile, rm } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';
import type { AssetManifest } from '@assets/manifest-types';
import { AssetCache } from './lib/cache.ts';
import { BuildContext } from './lib/context.ts';
import {
  Logger,
  MANIFEST_CSS,
  MANIFEST_TS,
  OUTPUT_ROOT,
  PUBLIC_PREFIX,
  ensureDir,
  walk,
  writeAtomic,
  writeIfChanged,
} from './lib/util.ts';
import { buildAudio } from './steps/audio.ts';
import { buildAvatars } from './steps/avatars.ts';
import { buildBackdrops } from './steps/backdrops.ts';
import { buildLogos } from './steps/logos.ts';
import { buildModels } from './steps/models.ts';
import { buildUi } from './steps/ui.ts';
import { buildVfx } from './steps/vfx.ts';
import { buildGeneratedAudio } from '../audio/build.ts';

const args = new Set(process.argv.slice(2));
const quiet = args.has('--quiet');
const force = args.has('--force');
const check = args.has('--check');

function renderManifestTs(manifest: AssetManifest): string {
  const keys = Object.keys(manifest.entries);
  const byPrefix = (prefix: string) => keys.filter((k) => k.startsWith(`${prefix}.`));
  const union = (list: string[]) => (list.length ? list.map((k) => `  | '${k}'`).join('\n') : '  | never');
  const kinds: Array<[string, string]> = [
    ['ModelKey', 'model'],
    ['AvatarKey', 'avatar'],
    ['BackdropKey', 'bg'],
    ['UiKey', 'ui'],
    ['DecoSheetKey', 'deco'],
    ['GlyphKey', 'glyph'],
    ['SpellKey', 'spell'],
    ['MusicKey', 'music'],
    ['AmbienceKey', 'ambience'],
    ['SfxKey', 'sfx'],
    ['FxKey', 'fx'],
    ['LogoKey', 'logo'],
  ];
  const lines = [
    '/* eslint-disable */',
    '// GENERATED by tools/assets/build.ts — do not edit. Run `pnpm assets:build`.',
    `export const MANIFEST_VERSION = '${manifest.version}';`,
    `export const MANIFEST_URL = '${PUBLIC_PREFIX}/manifest.json';`,
    `export const ASSET_COUNT = ${keys.length};`,
    '',
  ];
  for (const [name, prefix] of kinds) lines.push(`export type ${name} =\n${union(byPrefix(prefix))};`, '');
  lines.push(`export type AssetKey = ${kinds.map(([n]) => n).join(' | ')};`, '');
  // Deco frames live inside one packed sheet; their ids are typed but are not manifest entries.
  const sheet = manifest.entries['deco.sheet'];
  const decoFrames =
    sheet?.kind === 'atlas'
      ? Object.keys(sheet.frames)
          .sort()
          .map((f) => `deco.${f}`)
      : [];
  lines.push(
    '/** Frames of the packed pixel deco sheet (`deco.sheet`), cut and tinted at runtime (ADR-021). */',
    `export type DecoKey =\n${union(decoFrames)};`,
    '',
  );
  // Assets the loading screen needs before manifest.json has been fetched.
  const logo = manifest.entries['logo.chronicle_idle'];
  if (logo?.kind !== 'svg') throw new Error('Manifest is missing logo.chronicle_idle (svg)');
  lines.push(
    '/** URLs needed before the manifest is fetched (loading screen). */',
    `export const BOOT_ASSETS = { logo: '${logo.url}' } as const;`,
    '',
  );
  return lines.join('\n');
}

/** Minimal escaping for an SVG in a `url("data:image/svg+xml,…")` CSS value. */
function svgDataUri(svg: string): string {
  const compact = svg.replace(/\s+/g, ' ').replace(/> </g, '><').trim();
  const escaped = compact
    .replace(/"/g, "'")
    .replace(/%/g, '%25')
    .replace(/#/g, '%23')
    .replace(/</g, '%3C')
    .replace(/>/g, '%3E')
    .replace(/{/g, '%7B')
    .replace(/}/g, '%7D');
  return `data:image/svg+xml;charset=utf-8,${escaped}`;
}

/**
 * Kit textures as CSS variables (URLs) and glyphs inlined as data URIs, so the ~40 tiny glyph
 * files cost no requests at all (they are also emitted as files for Pixi).
 */
function renderCss(manifest: AssetManifest): string {
  const vars: string[] = [];
  for (const [key, entry] of Object.entries(manifest.entries)) {
    const name = `--${key.replace(/[._]/g, '-')}`;
    if (key.startsWith('ui.') && entry.kind === 'image') vars.push(`  ${name}: url("${entry.url}");`);
    if (key.startsWith('glyph.') && entry.kind === 'svg') {
      const rel = entry.url.slice(PUBLIC_PREFIX.length + 1);
      const svg = readFileSync(join(OUTPUT_ROOT, rel), 'utf8');
      vars.push(`  ${name}: url("${svgDataUri(svg)}");`);
    }
  }
  return [
    '/* GENERATED by tools/assets/build.ts — UI kit URLs and inlined glyphs as CSS variables. */',
    ':root {',
    ...vars.sort(),
    '}',
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const started = Date.now();
  const log = new Logger(quiet);
  await ensureDir(OUTPUT_ROOT);
  const cache = new AssetCache();
  await cache.load(force);
  const ctx = new BuildContext(cache, log);

  try {
    await Promise.all([
      buildModels(ctx),
      buildAvatars(ctx),
      buildUi(ctx),
      buildBackdrops(ctx),
      buildLogos(ctx),
      buildVfx(ctx),
    ]);
    await buildAudio(ctx);
    await buildGeneratedAudio(ctx);
  } catch (error) {
    // Keep what was produced so the next run resumes instead of starting over.
    await cache.save();
    throw error;
  }

  cache.prune();
  const manifest = ctx.manifest();
  const manifestJson = JSON.stringify(manifest);

  if (check) {
    const tsCurrent = existsSync(MANIFEST_TS) ? await readFile(MANIFEST_TS, 'utf8') : '';
    const cssCurrent = existsSync(MANIFEST_CSS) ? await readFile(MANIFEST_CSS, 'utf8') : '';
    const ok = tsCurrent === renderManifestTs(manifest) && cssCurrent === renderCss(manifest);
    if (!ok) {
      console.error(
        '[assets] generated manifest files are stale — run `pnpm assets:build` and commit the result.',
      );
      process.exit(1);
    }
    log.info('[assets] generated manifest files are up to date.');
  }

  await writeAtomic(join(OUTPUT_ROOT, 'manifest.json'), manifestJson);
  const tsChanged = await writeIfChanged(MANIFEST_TS, renderManifestTs(manifest));
  const cssChanged = await writeIfChanged(MANIFEST_CSS, renderCss(manifest));

  // Remove orphaned outputs (assets whose sources disappeared or changed).
  const keep = cache.outputs();
  keep.add('manifest.json');
  let removed = 0;
  for (const file of await walk(OUTPUT_ROOT)) {
    const rel = relative(OUTPUT_ROOT, file).split(sep).join('/');
    if (!keep.has(rel) && !rel.endsWith('.tmp')) {
      await rm(file);
      removed++;
    }
  }
  await cache.save();
  log.info(
    `[assets] ${manifest.entries && Object.keys(manifest.entries).length} entries · processed ${ctx.processed}, reused ${ctx.reused}, removed ${removed}` +
      ` · manifest ${manifest.version}${tsChanged || cssChanged ? ' (typed manifest updated)' : ''} · ${((Date.now() - started) / 1000).toFixed(1)}s`,
  );
}

main().catch((error: unknown) => {
  console.error('[assets] build failed:', error);
  process.exit(1);
});
