/**
 * ChronicleIdle asset pipeline. Reads the owner's sources in /game/assets and writes optimised,
 * content-hashed files to public/assets/generated plus a typed manifest (docs/tech/ARCHITECTURE.md §8).
 *
 *   tsx tools/assets/build.ts [--quiet] [--force] [--check]
 */
import { existsSync } from 'node:fs';
import { readFile, rm } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';
import type { AssetManifest } from '@assets/manifest-types';
import { AssetCache } from './lib/cache.ts';
import { BuildContext } from './lib/context.ts';
import { Logger, MANIFEST_CSS, MANIFEST_TS, OUTPUT_ROOT, PUBLIC_PREFIX, ensureDir, walk, writeAtomic, writeIfChanged } from './lib/util.ts';
import { buildAudio } from './steps/audio.ts';
import { buildAvatars } from './steps/avatars.ts';
import { buildBackdrops } from './steps/backdrops.ts';
import { buildLogos } from './steps/logos.ts';
import { buildModels } from './steps/models.ts';
import { buildUi } from './steps/ui.ts';
import { buildVfx } from './steps/vfx.ts';
import { buildGeneratedAudio } from '../audio/build.ts';

const args = new Set(process.argv.slice(2));
const quiet = args.has('--quiet');
const force = args.has('--force');
const check = args.has('--check');

function renderManifestTs(manifest: AssetManifest): string {
  const keys = Object.keys(manifest.entries);
  const byPrefix = (prefix: string) => keys.filter((k) => k.startsWith(`${prefix}.`));
  const union = (list: string[]) => (list.length ? list.map((k) => `  | '${k}'`).join('\n') : '  | never');
  const kinds: Array<[string, string]> = [
    ['ModelKey', 'model'], ['AvatarKey', 'avatar'], ['BackdropKey', 'bg'], ['UiKey', 'ui'], ['DecoKey', 'deco'], ['GlyphKey', 'glyph'],
    ['SpellKey', 'spell'], ['MusicKey', 'music'], ['AmbienceKey', 'ambience'], ['SfxKey', 'sfx'], ['FxKey', 'fx'], ['LogoKey', 'logo'],
  ];
  const lines = [
    '/* eslint-disable */',
    '// GENERATED by tools/assets/build.ts — do not edit. Run `pnpm assets:build`.',
    `export const MANIFEST_VERSION = '${manifest.version}';`,
    `export const MANIFEST_URL = '${PUBLIC_PREFIX}/manifest.json';`,
    `export const ASSET_COUNT = ${keys.length};`,
    '',
  ];
  for (const [name, prefix] of kinds) lines.push(`export type ${name} =\n${union(byPrefix(prefix))};`, '');
  lines.push(`export type AssetKey = ${kinds.map(([n]) => n).join(' | ')};`, '');
  return lines.join('\n');
}

function renderCss(manifest: AssetManifest): string {
  const vars: string[] = [];
  for (const [key, entry] of Object.entries(manifest.entries)) {
    if (!(key.startsWith('ui.') || key.startsWith('deco.') || key.startsWith('glyph.'))) continue;
    if (entry.kind !== 'image' && entry.kind !== 'svg') continue;
    vars.push(`  --${key.replace(/[._]/g, '-')}: url("${entry.url}");`);
  }
  return ['/* GENERATED by tools/assets/build.ts — UI kit, deco frame and glyph URLs as CSS variables. */', ':root {', ...vars.sort(), '}', ''].join('\n');
}

async function main(): Promise<void> {
  const started = Date.now();
  const log = new Logger(quiet);
  await ensureDir(OUTPUT_ROOT);
  const cache = new AssetCache();
  await cache.load(force);
  const ctx = new BuildContext(cache, log);

  try {
    await Promise.all([buildModels(ctx), buildAvatars(ctx), buildUi(ctx), buildBackdrops(ctx), buildLogos(ctx), buildVfx(ctx)]);
    await buildAudio(ctx);
    await buildGeneratedAudio(ctx);
  } catch (error) {
    // Keep what was produced so the next run resumes instead of starting over.
    await cache.save();
    throw error;
  }

  cache.prune();
  const manifest = ctx.manifest();
  const manifestJson = JSON.stringify(manifest);

  if (check) {
    const tsCurrent = existsSync(MANIFEST_TS) ? await readFile(MANIFEST_TS, 'utf8') : '';
    const cssCurrent = existsSync(MANIFEST_CSS) ? await readFile(MANIFEST_CSS, 'utf8') : '';
    const ok = tsCurrent === renderManifestTs(manifest) && cssCurrent === renderCss(manifest);
    if (!ok) {
      console.error('[assets] generated manifest files are stale — run `pnpm assets:build` and commit the result.');
      process.exit(1);
    }
    log.info('[assets] generated manifest files are up to date.');
  }

  await writeAtomic(join(OUTPUT_ROOT, 'manifest.json'), manifestJson);
  const tsChanged = await writeIfChanged(MANIFEST_TS, renderManifestTs(manifest));
  const cssChanged = await writeIfChanged(MANIFEST_CSS, renderCss(manifest));

  // Remove orphaned outputs (assets whose sources disappeared or changed).
  const keep = cache.outputs();
  keep.add('manifest.json');
  let removed = 0;
  for (const file of await walk(OUTPUT_ROOT)) {
    const rel = relative(OUTPUT_ROOT, file).split(sep).join('/');
    if (!keep.has(rel) && !rel.endsWith('.tmp')) {
      await rm(file);
      removed++;
    }
  }
  await cache.save();
  log.info(
    `[assets] ${manifest.entries && Object.keys(manifest.entries).length} entries · processed ${ctx.processed}, reused ${ctx.reused}, removed ${removed}` +
      ` · manifest ${manifest.version}${tsChanged || cssChanged ? ' (typed manifest updated)' : ''} · ${((Date.now() - started) / 1000).toFixed(1)}s`,
  );
}

main().catch((error: unknown) => {
  console.error('[assets] build failed:', error);
  process.exit(1);
});
