/**
 * Relics (docs/design/UNWRITTEN.md §8): each bends one rule of the expedition. Volume I is always
 * in the Unwritten; the Scriptorium's Third Volume adds the last eight.
 */
import { LAST_PAGE_SHARE, PHOENIX_SHARE } from '@content/balance/unwritten';
import {
  damage,
  flat,
  guard,
  inflict,
  meter,
  mend,
  onHit,
  onTurn,
  onWave,
  pct,
  relic,
  rule,
  statik,
} from './dsl';
import type { RelicDef } from './types';

export const RELICS: readonly RelicDef[] = [
  relic({
    slug: 'hourglass_of_embers',
    icon: 'spell.tech_chrono_watch',
    price: 130,
    values: { a: 20 },
    grant: ({ a }) => ({ passives: [onWave(meter(a, 'self'))] }),
  }),
  relic({
    slug: 'thornmail_shard',
    icon: 'spell.hunt_verdant_spikes',
    price: 120,
    values: { a: 20 },
    grant: ({ a }) => ({ passives: [statik({ kind: 'counterattack', chance: a })] }),
  }),
  relic({
    slug: 'wyrmscale_charm',
    icon: 'spell.hunt_jade_carapace',
    price: 120,
    values: { a: 8 },
    grant: ({ a }) => ({ passives: [statik(guard(a))] }),
  }),
  relic({
    slug: 'sigil_of_haste',
    icon: 'spell.rune_ember_mark',
    price: 140,
    values: { a: 8 },
    grant: ({ a }) => ({ passives: [statik(flat('spd', a))] }),
  }),
  relic({
    slug: 'heartseeker_lens',
    icon: 'spell.hunt_arrow_orb',
    price: 120,
    values: { a: 10 },
    grant: ({ a }) => ({ passives: [statik(flat('critRate', a))] }),
  }),
  relic({
    slug: 'vial_of_nightshade',
    icon: 'spell.hunt_emerald_orb',
    price: 110,
    values: { a: 12, t: 2 },
    grant: ({ a, t }) => ({ passives: [onHit(inflict('poison', t, 'single_enemy', a))] }),
  }),
  relic({
    slug: 'aegis_fragment',
    icon: 'spell.earth_gem_boulder',
    price: 120,
    values: { a: 10, t: 2 },
    grant: ({ a, t }) => ({ passives: [onWave(inflict('shield', t, 'self', 100, a))] }),
  }),
  relic({
    slug: 'iron_lung',
    icon: 'spell.earth_cobble_glow',
    price: 120,
    values: { a: 15 },
    grant: ({ a }) => ({ passives: [statik(pct('hp', a))] }),
  }),
  relic({
    slug: 'broken_quill',
    icon: 'spell.rune_fractured_stone',
    price: 150,
    values: { a: 1 },
    grant: ({ a }) => ({ rules: [rule('offer_size', a)] }),
  }),
  relic({
    slug: 'gilded_tongue',
    icon: 'spell.rune_jade_coin',
    price: 110,
    values: { a: 25 },
    grant: ({ a }) => ({ rules: [rule('price_mult', -a / 100)] }),
  }),
  relic({
    slug: 'pilgrims_lantern',
    icon: 'spell.tech_arc_lantern',
    price: 110,
    values: { a: 20 },
    grant: ({ a }) => ({ rules: [rule('rest_heal_mult', a / 100)] }),
  }),
  relic({
    slug: 'candle_of_vigil',
    icon: 'spell.fire_flame_drop',
    price: 130,
    values: { a: 6 },
    grant: ({ a }) => ({ rules: [rule('heal_after_victory', a / 100)] }),
  }),
  relic({
    slug: 'ledger_of_debts',
    icon: 'spell.rune_gilded_script',
    price: 110,
    values: { a: 20 },
    grant: ({ a }) => ({ rules: [rule('gilt_after_elite', a)] }),
  }),
  relic({
    slug: 'wardens_horn',
    icon: 'spell.tech_signal_horn',
    price: 140,
    values: { a: 15 },
    grant: ({ a }) => ({ rules: [rule('warden_hp', -a / 100)] }),
  }),
  relic({
    slug: 'phoenix_feather',
    icon: 'spell.fire_phoenix_flight',
    price: 150,
    // The share it rises at is the engine's own (`PHOENIX_SHARE`); the line only reports it.
    values: { a: Math.round(PHOENIX_SHARE * 100) },
    grant: () => ({ rules: [rule('phoenix', 1)] }),
  }),
  relic({
    slug: 'chroniclers_inkwell',
    icon: 'spell.blood_chalice',
    price: 110,
    values: { a: 1 },
    grant: ({ a }) => ({ rules: [rule('pages_per_passage', a)] }),
  }),

  // ── Volume III ──
  relic({
    slug: 'eclipse_shard',
    icon: 'spell.earth_crystal_meteor',
    volume: 3,
    price: 140,
    values: { a: 18, b: 8 },
    grant: ({ a, b }) => ({ passives: [statik(damage(a), pct('hp', -b))] }),
  }),
  relic({
    slug: 'wardens_bane',
    icon: 'spell.weapon_warhammer',
    volume: 3,
    price: 130,
    values: { a: 20 },
    grant: ({ a }) => ({ passives: [statik(damage(a))], only: ['warden'] }),
  }),
  relic({
    slug: 'huntsmans_mark',
    icon: 'spell.hunt_tracking_ring',
    volume: 3,
    price: 120,
    values: { a: 15 },
    grant: ({ a }) => ({ passives: [statik(damage(a))], only: ['elite'] }),
  }),
  relic({
    slug: 'choir_bell',
    icon: 'spell.fx_lotus_spring',
    volume: 3,
    price: 130,
    values: { a: 2 },
    grant: ({ a }) => ({ passives: [onTurn(mend(a, 'self'))] }),
  }),
  relic({
    slug: 'scholars_loupe',
    icon: 'spell.tech_compass',
    volume: 3,
    price: 150,
    values: { a: 25 },
    grant: ({ a }) => ({ rules: [rule('offer_rarity_bump', a / 100)] }),
  }),
  relic({
    slug: 'mercenarys_seal',
    icon: 'spell.rune_sealed_ring',
    volume: 3,
    price: 120,
    values: { a: 1 },
    grant: ({ a }) => ({ rules: [rule('echo_stars', a), rule('echo_full_hp', 1)] }),
  }),
  relic({
    slug: 'twin_moons',
    icon: 'spell.blood_crimson_moon',
    volume: 3,
    price: 150,
    values: { a: 1 },
    grant: ({ a }) => ({ rules: [rule('illumination_sooner', a)] }),
  }),
  relic({
    slug: 'the_last_page',
    icon: 'spell.rune_verdant_totem',
    volume: 3,
    price: 150,
    // As with the Phoenix Feather, the share is the engine's (`LAST_PAGE_SHARE`).
    values: { a: Math.round(LAST_PAGE_SHARE * 100) },
    grant: () => ({ rules: [rule('last_page', 1)] }),
  }),
];
